export const ocupaciones = [
  { id: '16', value: 'AU Règim especial d’autònoms' },
  { id: '15', value: 'RG Règim general' },
  { id: '6', value: 'EH Treballadors/ores de la llar' },
  { id: '1', value: 'FD Fixos discontinus en períodes de no-ocupació' },
  { id: '5', value: 'AP Administració pública' },
  {id: '2', value: 'RE Regulació d’ocupació en períodes de no-ocupació '}
]

export const documento = [
  { id: 0, letra: 'T' },
  { id: 1, letra: 'R' },
  { id: 2, letra: 'W' },
  { id: 3, letra: 'A' },
  { id: 4, letra: 'G' },
  { id: 5, letra: 'M' },
  { id: 6, letra: 'Y' },
  { id: 7, letra: 'F' },
  { id: 8, letra: 'P' },
  { id: 9, letra: 'D' },
  { id: 10, letra: 'X' },
  { id: 11, letra: 'B' },
  { id: 12, letra: 'N' },
  { id: 13, letra: 'J' },
  { id: 14, letra: 'Z' },
  { id: 15, letra: 'S' },
  { id: 16, letra: 'Q' },
  { id: 17, letra: 'V' },
  { id: 18, letra: 'H' },
  { id: 19, letra: 'L' },
  { id: 20, letra: 'C' },
  { id: 21, letra: 'K' },
  { id: 22, letra: 'E' },
]

export const procedencias = [
  { id: "1", value: "Oficina de Treball" },
  { id: "2", value: "Web del Consorci conforcatgencatcat" },
  { id: "3", value: "Cercador de cursos del SOC" },
  { id: "4", value: "Web fpgencatcat" },
  { id: "5", value: "Twitter (X) del Consorci @fpo_continua" },
  { id: "6", value: "Twitter (X) d'Ocupació @ocupaciocat" },
  { id: "7", value: "Entitat de formació" },
  { id: "8", value: "LinkedIn" },
  { id: "9", value: "Amics, amigues o familiars" },
  { id: "10", value: "Premsa, ràdio, televisió (mitjans comunicació)" },
  { id: "11", value: "Empresa" },
  { id: "12", value: "Agents econòmics i socials" },
  { id: "13", value: "Altres", valueb: 'Altres. Quins?', valuec: 'Altres.' },
  { id: "14", value: "Projectat orientació professional" },

]

export const generos = [
  { id: "0", value: 'Mujer', valuec: 'Dona' },
  { id: "1", value: 'Hombre', valuec: 'Home' },
  { id: "2", value: 'No binario', valuec: 'No binari' },
]

export const paises = [
  { id: "1", value: "Afganistan" },
  { id: "2", value: "Aland" },
  { id: "3", value: "Albània" },
  { id: "4", value: "Alemanya" },
  { id: "5", value: "Algèria" },
  { id: "6", value: "Andorra" },
  { id: "7", value: "Angola" },
  { id: "8", value: "Anguilla" },
  { id: "9", value: "Antàrtida" },
  { id: "10", value: "Antigua i Barbuda" },
  { id: "11", value: "Antilles Neerlandeses" },
  { id: "12", value: "Aràbia Saudí" },
  { id: "13", value: "Argentina", valuec: "Argentina" },
  { id: "14", value: "Armènia" },
  { id: "15", value: "Aruba" },
  { id: "16", value: "Austràlia" },
  { id: "17", value: "Àustria" },
  { id: "18", value: "Azerbaidjan" },
  { id: "19", value: "Bahames, les" },
  { id: "20", value: "Bahrain" },
  { id: "21", value: "Bangladesh" },
  { id: "22", value: "Barbados" },
  { id: "23", value: "Belarús" },
  { id: "24", value: "Bèlgica" },
  { id: "25", value: "Belize" },
  { id: "26", value: "Benín" },
  { id: "27", value: "Bermudes" },
  { id: "28", value: "Bhutan" },
  { id: "29", value: "Bolívia", valuec: "Bolivia" },
  { id: "30", value: "Bonaire, Sint Eustatius i Saba" },
  { id: "31", value: "Bòsnia i Hercegovina" },
  { id: "32", value: "Botswana" },
  { id: "33", value: "Brasil", valuec: "Brasil" },
  { id: "34", value: "Brunei" },
  { id: "35", value: "Bulgària" },
  { id: "36", value: "Burkina Faso" },
  { id: "37", value: "Burundi" },
  { id: "38", value: "Cambodja" },
  { id: "39", value: "Camerun" },
  { id: "40", value: "Canadà" },
  { id: "41", value: "Cap Verd" },
  { id: "42", value: "Ceuta" },
  { id: "43", value: "Colòmbia", valuec: 'Colombia' },
  { id: "44", value: "Comores, les" },
  { id: "45", value: "Congo" },
  { id: "46", value: "Corea del Nord" },
  { id: "47", value: "Corea del Sud" },
  { id: "48", value: "Costa d'Ivori" },
  { id: "49", value: "Costa Rica" },
  { id: "50", value: "Croàcia" },
  { id: "51", value: "Cuba" },
  { id: "52", value: "Curaçao" },
  { id: "53", value: "Dinamarca" },
  { id: "54", value: "Djibouti" },
  { id: "55", value: "Dominica" },
  { id: "56", value: "Egipte" },
  { id: "57", value: "El Salvador", valuec: "El Salvador" },
  { id: "58", value: "Emirats Àrabs Units, els" },
  { id: "59", value: "Equador", valuec: "Ecuador" },
  { id: "60", value: "Eritrea" },
  { id: "61", value: "Eslovàquia" },
  { id: "62", value: "Eslovènia" },
  { id: "63", value: "Espanya", valuec: "España" },
  { id: "64", value: "Estats Units, els" },
  { id: "65", value: "Estònia" },
  { id: "66", value: "Eswatini" },
  { id: "67", value: "Etiòpia" },
  { id: "68", value: "Fèroe" },
  { id: "69", value: "Fiji" },
  { id: "70", value: "Filipines" },
  { id: "71", value: "Finlàndia" },
  { id: "72", value: "França" },
  { id: "73", value: "Gabon" },
  { id: "74", value: "Gàmbia" },
  { id: "75", value: "Geòrgia" },
  { id: "76", value: "Ghana" },
  { id: "77", value: "Gibraltar" },
  { id: "78", value: "Grècia" },
  { id: "79", value: "Grenada" },
  { id: "80", value: "Groenlàndia" },
  { id: "81", value: "Guadalupe" },
  { id: "82", value: "Guaiana Francesa" },
  { id: "83", value: "Guam" },
  { id: "84", value: "Guatemala" },
  { id: "85", value: "Guernsey" },
  { id: "86", value: "Guinea" },
  { id: "87", value: "Guinea Equatorial" },
  { id: "88", value: "Guinea-Bissau" },
  { id: "89", value: "Guyana" },
  { id: "90", value: "Haití" },
  { id: "91", value: "Hondures", valuec: "Honduras" },
  { id: "92", value: "Hong Kong, Xina" },
  { id: "93", value: "Hongria" },
  { id: "94", value: "Iemen, el" },
  { id: "95", value: "Illa Bouvet" },
  { id: "96", value: "Illa Christmas" },
  { id: "97", value: "Illa de Man" },
  { id: "98", value: "Illa Norfolk" },
  { id: "99", value: "Illes Caiman" },
  { id: "100", value: "Illes Cocos (Keeling)" },
  { id: "101", value: "Illes Cook" },
  { id: "102", value: "Illes del Canal" },
  { id: "103", value: "Illes Falkland (Malvines)" },
  { id: "104", value: "Illes Geòrgia del Sud i Sandwich del Sud" },
  { id: "105", value: "Illes Heard i McDonald" },
  { id: "106", value: "Illes Marianes del Nord" },
  { id: "107", value: "Illes Marshall" },
  { id: "108", value: "Illes Menors Allunyades dels Estats Units" },
  { id: "109", value: "Illes Salomó" },
  { id: "110", value: "Illes Turks i Caicos" },
  { id: "111", value: "Illes Verges Britàniques" },
  { id: "112", value: "Illes Verges dels Estats Units" },
  { id: "113", value: "Índia" },
  { id: "114", value: "Indonèsia" },
  { id: "115", value: "Iran" },
  { id: "116", value: "Iraq, l'" },
  { id: "117", value: "Irlanda" },
  { id: "118", value: "Islàndia" },
  { id: "119", value: "Israel" },
  { id: "120", value: "Itàlia", valuec: "Italia" },
  { id: "121", value: "Jamaica" },
  { id: "122", value: "Japó" },
  { id: "123", value: "Jersey" },
  { id: "124", value: "Jordània" },
  { id: "125", value: "Kazakhstan" },
  { id: "126", value: "Kenya" },
  { id: "127", value: "Kirguizstan" },
  { id: "128", value: "Kiribati" },
  { id: "129", value: "Kosovo" },
  { id: "130", value: "Kuwait" },
  { id: "131", value: "Lao" },
  { id: "132", value: "Lesotho" },
  { id: "133", value: "Letònia" },
  { id: "134", value: "Líban" },
  { id: "135", value: "Libèria" },
  { id: "136", value: "Líbia" },
  { id: "137", value: "Liechtenstein" },
  { id: "138", value: "Lituània" },
  { id: "139", value: "Luxemburg" },
  { id: "140", value: "Macao, Xina" },
  { id: "141", value: "Macedònia del Nord" },
  { id: "142", value: "Madagascar" },
  { id: "143", value: "Malàisia" },
  { id: "144", value: "Malawi" },
  { id: "145", value: "Maldives" },
  { id: "146", value: "Mali" },
  { id: "147", value: "Malta" },
  { id: "148", value: "Marroc, el", valuec: "Marruecos" },
  { id: "149", value: "Martinica" },
  { id: "150", value: "Maurici" },
  { id: "151", value: "Mauritània" },
  { id: "152", value: "Mayotte" },
  { id: "153", value: "Melilla" },
  { id: "154", value: "Mèxic" },
  { id: "155", value: "Micronèsia" },
  { id: "156", value: "Moçambic" },
  { id: "157", value: "Moldàvia" },
  { id: "158", value: "Mònaco" },
  { id: "159", value: "Mongòlia" },
  { id: "160", value: "Montenegro" },
  { id: "161", value: "Montserrat" },
  { id: "162", value: "Myanmar" },
  { id: "163", value: "Namíbia" },
  { id: "164", value: "Nauru" },
  { id: "165", value: "Nepal" },
  { id: "166", value: "Nicaragua" },
  { id: "167", value: "Níger" },
  { id: "168", value: "Nigèria" },
  { id: "169", value: "Niue" },
  { id: "170", value: "Noruega" },
  { id: "171", value: "Nova Caledònia" },
  { id: "172", value: "Nova Zelanda" },
  { id: "173", value: "Oman" },
  { id: "174", value: "Països Baixos" },
  { id: "175", value: "Pakistan" },
  { id: "176", value: "Palau" },
  { id: "177", value: "Palestina" },
  { id: "178", value: "Panamà", value: "Panama" },
  { id: "179", value: "Papua Nova Guinea" },
  { id: "180", value: "Paraguai", valuec: "Paraguay" },
  { id: "181", value: "Perú", valuec: "Peru" },
  { id: "182", value: "Pitcairn" },
  { id: "183", value: "Polinèsia Francesa" },
  { id: "184", value: "Polònia" },
  { id: "185", value: "Portugal" },
  { id: "186", value: "Puerto Rico" },
  { id: "187", value: "Qatar" },
  { id: "188", value: "Regne Unit" },
  { id: "189", value: "República Centreafricana" },
  { id: "190", value: "República Democràtica del Congo" },
  { id: "191", value: "Republica Dominicana", valuec: "República Dominicana" },
  { id: "192", value: "Reunió, la" },
  { id: "193", value: "Romania", valuec: "Rumania" },
  { id: "194", value: "Ruanda" },
  { id: "195", value: "Rússia" },
  { id: "196", value: "Sàhara Occidental" },
  { id: "197", value: "Saint Helena, Ascenció i Tristan da Cunha" },
  { id: "198", value: "Saint Kitts i Nevis" },
  { id: "199", value: "Saint Lucia" },
  { id: "200", value: "Saint Vincent i les Grenadines" },
  { id: "201", value: "Saint-Barthélemy" },
  { id: "202", value: "Saint-Martin" },
  { id: "203", value: "Saint-Pierre-et-Miquelon" },
  { id: "204", value: "Samoa" },
  { id: "205", value: "Samoa Americana" },
  { id: "206", value: "San Marino" },
  { id: "207", value: "Santa Seu" },
  { id: "208", value: "São Tomé i Príncipe" },
  { id: "209", value: "Sark" },
  { id: "210", value: "Senegal" },
  { id: "211", value: "Sèrbia" },
  { id: "212", value: "Seychelles" },
  { id: "213", value: "Sierra Leone" },
  { id: "214", value: "Singapur" },
  { id: "215", value: "Sint Maarten" },
  { id: "216", value: "Síria" },
  { id: "217", value: "Somàlia" },
  { id: "218", value: "Sri Lanka" },
  { id: "219", value: "Sud-àfrica" },
  { id: "220", value: "Sudan del Sud, el" },
  { id: "221", value: "Sudan, el" },
  { id: "222", value: "Suècia" },
  { id: "223", value: "Suïssa" },
  { id: "224", value: "Surinam" },
  { id: "225", value: "Svalbard i Jan Mayen" },
  { id: "226", value: "Tadjikistan" },
  { id: "227", value: "Tailàndia" },
  { id: "228", value: "Taiwan" },
  { id: "229", value: "Tanzània" },
  { id: "230", value: "Terres Australs i Antàrtiques Franceses" },
  { id: "231", value: "Territori Britànic de l'Oceà Índic" },
  { id: "232", value: "Timor-Leste" },
  { id: "233", value: "Togo" },
  { id: "234", value: "Tokelau" },
  { id: "235", value: "Tonga" },
  { id: "236", value: "Trinidad i Tobago" },
  { id: "237", value: "Tunísia" },
  { id: "238", value: "Turkmenistan" },
  { id: "239", value: "Turquia" },
  { id: "240", value: "Tuvalu" },
  { id: "241", value: "Txad" },
  { id: "242", value: "Txèquia" },
  { id: "243", value: "Ucrania", valuec:"ucrania" },
  { id: "244", value: "Uganda" },
  { id: "245", value: "Uruguai", valuec:"Uruguay" },
  { id: "246", value: "Uzbekistan" },
  { id: "247", value: "Vanuatu" },
  { id: "248", value: "Veneçuela", valuec: "Venezuela" },
  { id: "249", value: "Vietnam" },
  { id: "250", value: "Wallis i Futuna" },
  { id: "251", value: "Xile" },
  { id: "252", value: "Xina" },
  { id: "253", value: "Xipre" },
  { id: "254", value: "Zàmbia" },
  { id: "255", value: "Zimbàbue" },
]

export const intereses = [
  { id: "1", value: "- Para adquirir competencias no demostradas en acreditación de competencias (continuidad formativa)", valuec: "Per adquirir competències no demostrades en acreditació de competències (continuïtat formativa)" },
  { id: "2", value: "- Para mejorar mi cualificación", valuec: "Per millorar la meva qualificació" },
  { id: "3", value: "- Para actualizar competencias y adaptarme a los cambios de mi puesto de trabajo", valuec: "Per actualitzar competències i adaptar-me als canvis del meu lloc de treball" },
  { id: "4", value: "Per canviar de feina", valuec: "" },
  { id: "5", value: "- Para adquirir habilidades personales", valuec: "Per adquirir habilitats personals" },
  { id: "6", value: "- Otros", valuec: "Altres" },
]

export const baseCategorias = [
  { id: '881', id2: '901', id3: "941", value: "No aplicable", valueb: "-", valuec: "-" },
  { id: '882', id2: '902', id3: "942", value: "Desocupats / Desocupades", valuec: "" },
  { id: '883', id2: '903', id3: "943", value: "Treballador/a de baixa qualificació2", valuec: "- Trabajador/a de baja cualificación", valueb: "- Treballador/a de baixa qualificació (2)" },
  { id: '884', id2: '904', id3: "944", value: "Comandaments intermedis", valueb: "Comandament intermedi", valuec: "- Mandos intermedios" },
  { id: '885', id2: '905', id3: "945", value: "Tècnics / Tècniques", valueb: "Tècnic/a", valuec: "- Técnico/a" },
  { id: '886', id2: '906', id3: "946", value: "Treballadors/ores qualificats/des", valueb: "Treballador/a qualificat/ada", valuec: "- Trabajador/a cualificado/a" },
  { id: '887', id2: '907', id3: "947", value: "Directius / Directives", valueb: "Directiu/iva", valuec: "- Mandos intermedios" },
]

export const baseEstudios = [
  { id: "1", value: "Sense titulació", valuec: "- Sin titulación" },
  { id: "2", value: "Títol de graduat ESO / graduat escolar", valuec: "- Título de graduado ESO / graduado escolar" },
  { id: "3", value: "Títol de batxillerat", valuec: "- Título de bachillerato" },
  { id: "4", value: "Títol de tècnic/a / FP grau mitjà / Cert. de Prof.* Nivell 2", valuec: "- Título de técnico/a / FP grado medio / Certificado profesional de nivel 2" },
  { id: "5", value: "Títol de tècnic/a Superior / FP grau superior / Cert. de Prof.* Nivell 3", valuec: "- Título de técnico/a Superior / FP grado superior / Certificado profesional de nivel 3" },
  { id: "6", value: "Estudis universitaris de 1r Cicle (diplomatura-grau)", valuec: "- Estudios universitarios de 1er Ciclo (diplomatura-grado)" },
  { id: "7", value: "Estudis universitaris de 2n Cicle (llicenciatura-màster)", valuec: "- Estudios universitarios de 2º Ciclo (licenciatura-máster)" },
  { id: "8", value: "Estudis universitaris de 3r Cicle (doctorat)", valuec: "- Estudios universitarios de 3er Ciclo (doctorado)" },
  { id: "10", value: "Altra titulació. Especificar", valuec: "- Otra titulación" },
  { id: "11", value: "Títol de FP bàsica / Cert. de Prof.* Nivell 1", valuec: "- Título de FP básica / Certificado profesional de nivel 1" },
]

export const baseMedidaEmpresa = [
  { id: "0", value: "(cap)", valuec: "-" },
  { id: "1", value: "De 1 a 9 persones treballadores", valuec: "- De 1 a 9 personas trabajadoras" },
  { id: "2", value: "De 10 a 49 persones treballadores", valuec: "- De 10 a 49 personas trabajadoras" },
  { id: "3", value: "De 50 a 249 persones treballadores", valuec: "- De 50 a 249 personas trabajadoras" },
  { id: "4", value: "Més de 250 persones treballadores", valuec: "- Más de 249 personas trabajadoras" },
]
